// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZaaBkZxQfZJTSfKFXIe3M0lo-uq07HE',
    appId: '1:546499193705:web:aecbfdf398a065547aabf8',
    messagingSenderId: '546499193705',
    projectId: 'gym-tracker-8b066',
    authDomain: 'gym-tracker-8b066.firebaseapp.com',
    storageBucket: 'gym-tracker-8b066.firebasestorage.app',
    measurementId: 'G-QDBTJHSQFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMP0jF5xQJyMBEp8LcoCEeNFh7W1SAFfE',
    appId: '1:546499193705:android:3371ab57482c5fe87aabf8',
    messagingSenderId: '546499193705',
    projectId: 'gym-tracker-8b066',
    storageBucket: 'gym-tracker-8b066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUC0E_e3ANBhkW5pHr0iJzPLpYRHjoOE',
    appId: '1:546499193705:ios:dcf4315004a0f25d7aabf8',
    messagingSenderId: '546499193705',
    projectId: 'gym-tracker-8b066',
    storageBucket: 'gym-tracker-8b066.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArUC0E_e3ANBhkW5pHr0iJzPLpYRHjoOE',
    appId: '1:546499193705:ios:dcf4315004a0f25d7aabf8',
    messagingSenderId: '546499193705',
    projectId: 'gym-tracker-8b066',
    storageBucket: 'gym-tracker-8b066.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnZaaBkZxQfZJTSfKFXIe3M0lo-uq07HE',
    appId: '1:546499193705:web:2931f85ea7b967b47aabf8',
    messagingSenderId: '546499193705',
    projectId: 'gym-tracker-8b066',
    authDomain: 'gym-tracker-8b066.firebaseapp.com',
    storageBucket: 'gym-tracker-8b066.firebasestorage.app',
    measurementId: 'G-HK794CZ3Q4',
  );
}
